image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Clone to GitHub
          script:
            - git clone git@bitbucket.org:visitor1/visitor-front.git
            - ls
            - cd visitor-front
            - git push --mirror git@github.com:Spaguetto/vasitor-front-GH.git